apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gateway-service
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - acmecorp
  selector:
    matchLabels:
      app: gateway-service
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
      relabelings:
        - sourceLabels: [__meta_kubernetes_service_label_app]
          targetLabel: application
          action: replace
