services:
  prometheus:
    image: prom/prometheus:v2.53.1
    container_name: acmecorp-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./observability/prometheus/rules:/etc/prometheus/rules:ro
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=7d
    depends_on:
      - alertmanager

  alertmanager:
    image: prom/alertmanager:v0.27.0
    container_name: acmecorp-alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./observability/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
    command:
      - --config.file=/etc/alertmanager/alertmanager.yml
      - --storage.path=/alertmanager

  grafana:
    image: grafana/grafana:10.4.5
    container_name: acmecorp-grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - ./observability/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./observability/grafana/dashboards:/var/lib/grafana/dashboards:ro
    depends_on:
      - prometheus

  k6:
    image: grafana/k6:0.49.0
    container_name: acmecorp-k6
    profiles:
      - load
    environment:
      BASE_URL: http://gateway-service:8080
      RATE: "2"
      DURATION: "30m"
    volumes:
      - ./loadtests:/scripts:ro
    command: ["run", "/scripts/k6-unicorn.js"]
    depends_on:
      - gateway-service
    restart: "no"
