version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: acmecorp-postgres
    environment:
      POSTGRES_DB: acmecorp
      POSTGRES_USER: acmecorp
      POSTGRES_PASSWORD: acmecorp
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: acmecorp-redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: acmecorp-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  orders-service:
    build: ../../services/spring-boot/orders-service
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8081:8081"

  billing-service:
    build: ../../services/spring-boot/billing-service
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8082:8082"

  notification-service:
    build: ../../services/spring-boot/notification-service
    depends_on:
      - postgres
      - rabbitmq
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8083:8083"

  analytics-service:
    build: ../../services/spring-boot/analytics-service
    depends_on:
      - postgres
      - redis
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8084:8084"

  catalog-service:
    build: ../../services/quarkus/catalog-service
    depends_on:
      - postgres
    ports:
      - "8085:8085"

  gateway-service:
    build: ../../services/spring-boot/gateway-service
    depends_on:
      - orders-service
      - catalog-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"

volumes:
  pgdata:
