{{- if .Values.ordersService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: orders-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: orders-service
spec:
  type: ClusterIP
  selector:
    app: orders-service
  ports:
    - port: 80
      targetPort: {{ .Values.ordersService.port }}
      name: http
{{- end }}
