{{- if .Values.redis.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: acmecorp-redis-config
  namespace: {{ .Values.global.namespace }}
data:
  REDIS_HOST: redis
  REDIS_PORT: {{ .Values.redis.port | quote }}
{{- end }}
