apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "catalog-service.fullname" . }}-config
  labels:
    {{- include "catalog-service.labels" . | nindent 4 }}
data:
  QUARKUS_DATASOURCE_JDBC_URL: {{ .Values.config.jdbcUrl | quote }}
  QUARKUS_DATASOURCE_USERNAME: {{ .Values.config.username | quote }}
