apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "catalog-service.fullname" . }}
  labels:
    {{- include "catalog-service.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "catalog-service.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "catalog-service.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "catalog-service.serviceAccountName" . }}
      {{- $pullSecrets := .Values.imagePullSecrets }}
      {{- if not $pullSecrets }}
      {{- with .Values.global }}
      {{- $pullSecrets = .imagePullSecrets }}
      {{- end }}
      {{- end }}
      {{- if $pullSecrets }}
      imagePullSecrets:
{{ toYaml $pullSecrets | nindent 6 }}
      {{- end }}
      containers:
        - name: catalog
          {{- $secretName := default (printf "%s-secret" (include "catalog-service.fullname" .)) .Values.secret.name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: QUARKUS_DATASOURCE_JDBC_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "catalog-service.fullname" . }}-config
                  key: QUARKUS_DATASOURCE_JDBC_URL
            - name: QUARKUS_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "catalog-service.fullname" . }}-config
                  key: QUARKUS_DATASOURCE_USERNAME
            - name: QUARKUS_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}
                  key: password
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
          {{- if .Values.probes.enabled }}
          livenessProbe:
            httpGet:
              path: /q/health/ready
              port: {{ .Values.service.port }}
            initialDelaySeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /q/health/ready
              port: {{ .Values.service.port }}
            initialDelaySeconds: 15
            timeoutSeconds: 3
          {{- end }}
