{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default (printf "%s-secret" (include "catalog-service.fullname" .)) .Values.secret.name }}
  labels:
    {{- include "catalog-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- with .Values.secret.data }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
