apiVersion: v1
kind: Service
metadata:
  name: {{ include "catalog-service.fullname" . }}
  labels:
    {{- include "catalog-service.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.prometheus.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: ClusterIP
  selector:
    {{- include "catalog-service.labels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
