apiVersion: v1
kind: Secret
metadata:
  name: acmecorp-credentials
  namespace: acmecorp
type: Opaque
stringData:
  POSTGRES_DB: acmecorp
  POSTGRES_USER: acmecorp
  POSTGRES_PASSWORD: acmecorp
  RABBITMQ_USERNAME: guest
  RABBITMQ_PASSWORD: guest
