apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: acmecorp
resources:
  - namespace.yaml
  - orders-service-deployment.yaml
  - orders-service-service.yaml
  - billing-service-deployment.yaml
  - billing-service-service.yaml
  - notification-service-deployment.yaml
  - notification-service-service.yaml
  - analytics-service-deployment.yaml
  - analytics-service-service.yaml
  - catalog-service-deployment.yaml
  - catalog-service-service.yaml
  - gateway-service-deployment.yaml
  - gateway-service-service.yaml
  - gateway-ingress.yaml
