apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gateway-service.fullname" . }}-config
  labels:
    {{- include "gateway-service.labels" . | nindent 4 }}
data:
  ORDERS_BASE_URL: {{ .Values.config.ordersBaseUrl | quote }}
  CATALOG_BASE_URL: {{ .Values.config.catalogBaseUrl | quote }}
  BILLING_BASE_URL: {{ .Values.config.billingBaseUrl | quote }}
  NOTIFICATION_BASE_URL: {{ .Values.config.notificationBaseUrl | quote }}
  ANALYTICS_BASE_URL: {{ .Values.config.analyticsBaseUrl | quote }}
  SPRING_PROFILES_ACTIVE: {{ .Values.config.springProfilesActive | quote }}
